services:
  postgres:
    image: postgres:16-alpine
    container_name: atak_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: atak_db
    ports:
      - "5433:5432"
    volumes:
      - atak_pg_data:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  minio:
    image: quay.io/minio/minio
    container_name: atak_minio
    restart: unless-stopped
    command: server /data --console-address ':9001'
    environment:
      MINIO_ROOT_USER: atakadmin
      MINIO_ROOT_PASSWORD: atakadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - atak_minio_data:/data

  atak-server:
    image: atak-mi-server:latest
    container_name: atak-mi-server
    restart: unless-stopped
    depends_on:
      - postgres
      - minio
    environment:
      RELAY_MODE: "false"
      PORT: "3001"
      SERVER_URL: "http://100.83.151.84:3001"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: atak_db
      MINIO_ENDPOINT: minio
      MINIO_PORT: "9000"
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: atakadmin
      MINIO_SECRET_KEY: atakadmin123
      MQTT_ENABLED: "false"
      JWT_SECRET_KEY: "tactical-secret-change-me"
    ports:
      - "3001:3001"

volumes:
  atak_pg_data:
  atak_minio_data:
